travis:
  secure:
    BINSTAR_TOKEN: Yl9VpCWtExfSOm4LBPSOIqh9Q1tF1lazbIK46TQfX6fi7ou8K9Ur2ULkk3ZhHRnL1mXxYSFfVfT1RaMbXpUo8eKjoPIo5U2e+47OfmAZPFMxk6ucRTlS2YmcJunOvqFcAlcE9MYt4catSkiNE2WZr60EyUpW+WGnxhMdiLB7O/B4g7oFu93ML9LpbQQHrCRdLd3aTYNGAD5NRjY4iYbh5hWhiOgKLI4TihxFH21jsfKmwbE7h+3bEhN70igX3NtSPq7540ZBreM1I/ySbqhgrGeXbAppMRvbFUAz44TGoOugbNkr7Xe81jOAVXlrkctB/DGFKvJ8869gwO7EMR86PydfEmX/zuIksTv3JOS+AG4LpN9JKyJ+VVQlCuVV7ds+kDtiLaTSbhv7yyVn5uEys2N8qeNWOAemQfxrWcZFP7ATYlW7MQjGRj4y2qd53/zTqtn6djXkK/sZSaWPl+ItLoe1acfGY/YUy6Czvq3wktYVkxxcjEArjOr8BQ+i3GtPPXWwn1jQXc3OT9Va0Jl+gzOCQI4wbsGXi9GQvzU/DGg7lBfOFMAgValGow0IWcU9+FE8xH28hqb/U3kcS91BhYll1ErBuNG3No1mktH7n+m+XMQYepC30NMPMWHud6/1qczrSNxA7H+gcOm9ojmI1PBBnHzrrqcPDRn1YSe1CN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
